name       : cheese
version    : '41.1'
release    : 23
homepage   : https://wiki.gnome.org/Apps/Cheese
source     :
    - https://download.gnome.org/sources/cheese/41/cheese-41.1.tar.xz : 522960ca28730ff66439070b04418c9e0a4bb55560d75bfe08b218da2c67e547
license    : GPL-2.0-or-later
component  :
    - multimedia.video
    - ^libcheese : multimedia.library
summary    :
    - Take photos and videos with your webcam, with fun graphical effects
    - ^libcheese : Library for taking photos and videos with your webcam
description: |
    Uses your webcam to take photos and videos, applies fancy special effects, and lets you share the fun with others.
builddeps  :
    - pkgconfig(clutter-gst-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-video-effects)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(x11)
    - gtk-doc
    - itstool
    - vala
rundeps    :
    - ^libcheese : gnome-video-effects
patterns   :
    - ^libcheese :
        - /usr/lib64/libcheese*.so.*
        - /usr/share/glib-2.0/schemas/org.gnome.Cheese.gschema.xml
        - /usr/lib/girepository-1.0/Cheese-3.0.typelib
        - /usr/share/gir-1.0/Cheese-3.0.gir
setup      : |
    %patch -p1 < $pkgfiles/0001-Update-for-new-gnome-desktop-api.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
