name       : cheese
version    : 3.26.0
release    : 10
homepage   : https://wiki.gnome.org/Apps/Cheese
source     :
    - https://download.gnome.org/sources/cheese/3.26/cheese-3.26.0.tar.xz : 8ef52fc41de1817c4e4274e23eb7c29d28b64ae0f0d1fec52e184e99aea6c605
license    : GPL-2.0
clang      : no
component  : multimedia.video
summary    : Cheese Webcam App
description: |
    Uses your webcam to take photos and videos, applies fancy special effects \nand lets you share the fun with others.
builddeps  :
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gst-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(glib-2.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(gnome-video-effects)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(x11)
    - itstool
rundeps    :
    - gnome-video-effects
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
