name       : cheese
version    : 3.18.1
release    : 3
homepage   : https://wiki.gnome.org/Apps/Cheese
source     :
    - http://ftp.gnome.org/pub/gnome/sources/cheese/3.18/cheese-3.18.1.tar.xz : fc9d8798b1f0c6b35731f063869a32c6910bab6d0386b9ea36386ebda0d57177
license    : GPL-2.0
summary    : Cheese Webcam App
builddeps  :
    - itstool
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gst-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(x11)
    - pkgconfig(gnome-video-effects)
rundeps    :
    - gnome-video-effects
description: |
    Uses your webcam to take photos and videos, applies fancy special effects 
    and lets you share the fun with others.
clang      : no
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
