name       : cheese
version    : 3.20.2
release    : 7
homepage   : https://wiki.gnome.org/Apps/Cheese
source     :
    - http://ftp.gnome.org/pub/gnome/sources/cheese/3.20/cheese-3.20.2.tar.xz : b7c18719b708e039c063ef09278ee813923556e06af4a7e9598c5d3bdeb83775
license    : GPL-2.0
clang      : no
component  : multimedia.video
summary    : Cheese Webcam App
description: "Uses your webcam to take photos and videos, applies fancy special effects \nand lets you share the fun with others.\n"
builddeps  :
    - itstool
    - pkgconfig(glib-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(gstreamer-plugins-bad-1.0)
    - pkgconfig(gnome-desktop-3.0)
    - pkgconfig(clutter-1.0)
    - pkgconfig(clutter-gst-3.0)
    - pkgconfig(clutter-gtk-1.0)
    - pkgconfig(libcanberra-gtk3)
    - pkgconfig(x11)
    - pkgconfig(gnome-video-effects)
rundeps    :
    - gnome-video-effects
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
